//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPM02AutoShow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PM02AutoShowBDEntities1 : DbContext
    {
        private static PM02AutoShowBDEntities1 _context;
        public PM02AutoShowBDEntities1()
            : base("name=PM02AutoShowBDEntities1")
        {
        }

        public static PM02AutoShowBDEntities1 GetContext()
        {
            if (_context == null)
                _context = new PM02AutoShowBDEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Договоры> Договоры { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<СистемаПодачиТоплива> СистемаПодачиТоплива { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СпособыОплаты> СпособыОплаты { get; set; }
        public virtual DbSet<ТестДрайв> ТестДрайв { get; set; }
        public virtual DbSet<ТипДвигателя> ТипДвигателя { get; set; }
    }
}
