//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPM02AutoShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договоры
    {
        public int id_Договора { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public Nullable<int> КодАвтомобиля { get; set; }
        public Nullable<int> КодКлиента { get; set; }
        public Nullable<int> КодСпособаОплаты { get; set; }
        public string СтатусВыполнения { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual СпособыОплаты СпособыОплаты { get; set; }
    }
}
