//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPM02AutoShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Договоры = new HashSet<Договоры>();
        }
    
        public int id_Сотрудника { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> КодДолжности { get; set; }
        public string ДатаРождения { get; set; }
        public string ДатаПриёмаНаРаботу { get; set; }
        public string Зарплата { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договоры> Договоры { get; set; }
        public virtual Должности Должности { get; set; }
    }
}
