//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPM02AutoShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТестДрайв
    {
        public int id_ТестДрайв { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Время { get; set; }
        public Nullable<int> КодАвтомобиля { get; set; }
        public string СтатусВыполнения { get; set; }
        public string Примечание { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
    }
}
