//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalonWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобили()
        {
            this.Договоры = new HashSet<Договоры>();
            this.ТестДрайв = new HashSet<ТестДрайв>();
        }
    
        public int id_Автомобиля { get; set; }
        public string Марка { get; set; }
        public Nullable<int> КодПоставщика { get; set; }
        public string Цвет { get; set; }
        public string КоличествоМест { get; set; }
        public string МаксимальнаяСкорость { get; set; }
        public Nullable<int> КодТипаДвигателя { get; set; }
        public string РабочийОбъёмДвигателя { get; set; }
        public Nullable<int> КодСистемыПодачиТоплива { get; set; }
        public string РасходТоплива { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string ВНаличии { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual СистемаПодачиТоплива СистемаПодачиТоплива { get; set; }
        public virtual ТипДвигателя ТипДвигателя { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договоры> Договоры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТестДрайв> ТестДрайв { get; set; }
    }
}
